config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:new, :create, :index] do
    resources :tasks, only: [:create, :index] do
      post :finish
    end
  end

  resources :tasks, only: [] do
    post :finish
  end

  devise_for :users, controllers: {
    sessions:    "users/sessions",
    registrations: "users/registrations"
  }

  root to: "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true, allow_blank: false

  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, allow_blank: false

  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pagy::Backend

  # protect_from_forgery with: :exception


  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.create(project_params)
    redirect_to project_tasks_url(@project)
  end

  private

  def project_params
    params.require(:project).permit(:title)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @projects = current_user.projects
    @current_project = Project.find(params[:project_id])

    @pagy, @tasks = pagy(@current_project.tasks.order(created_at: :desc), items: 10)


    @tasks_presenter = {
      tasks: @tasks,
      form: {
        action: project_tasks_url(@current_project.id),
        csrf_param: request_forgery_protection_token,
        csrf_token: form_authenticity_token
      }
    }
  end

  def create
    @current_project = Project.find(params[:project_id])
    task = @current_project.tasks.build(tasks_params)
    task.started_at = DateTime.current
    task.save

    render json: task
  end

  def finish
    @task = Task.find(params[:task_id])

    @task.update(finished_at: DateTime.current)

    render json: @task
  end

  private

  def tasks_params
    params.require(:task).permit(:id, :content, :project_id)
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    layout "onboard"
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    layout "onboard"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracker</title>
    <%= csrf_meta_tags %>

    <!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <script>
      document.getElementsByTagName('html')[0].className = 'js ' + ((/android|webos|iphone|ipad|ipod|blackberry|iemobile|opera mini/i.test(navigator.userAgent.toLowerCase())) ? 'mobile' : 'desktop');
    </script>

    <%= stylesheet_link_tag 'application', media: 'all' %>

  </head>

  <body>
    <header class="header header-main">
      <div class="wrapper">
        <%= current_user.email %>
        <div class="user">
          <%= image_tag "star-lord.jpg" %>
        </div>
        <div class="clr"></div>
      </div>
    </header>

    <%= yield %>

    <footer class="footer footer-main">
      <div class="wrapper">

      </div>
    </footer>

    <%= javascript_include_tag 'application' %>

  </body>
</html>

app/views/layouts/onboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <style type="text/css">
    body {
      background-color: #DADADA;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {
      max-width: 450px;
    }
  </style>
  <%= csrf_meta_tags %>
</head>
<body class="background-big">
  <div class="ui middle aligned center aligned grid">
    <div class="column">
      <h2 class="ui grey image header">Timetracker</h2>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/projects/index.slim
ul
  - @projects.each do |project|
    li
      = link_to project.title, project_tasks_url(project)

= link_to "new project", new_project_url

app/views/projects/new.slim
= simple_form_for @project do |f|
  = f.input :title
  = f.submit

app/views/tasks/index.html.slim
header class="header header-left"
  .wrapper
    .logo
      a href="/" Timetracker
    nav class="main-menu"
      ul
        - @projects.each do |project|
          li
            = active_link_to project_tasks_url(project) do
              svg height="19"
                g xmlns="http://www.w3.org/2000/svg"
                  path d="M8.60213825,3.58050375 L8.60213825,2.37204682 L11.0599078,2.37204682 L11.0599078,1.18600562 C11.0599078,0.531003745 10.5096774,0 9.83096774,0 L6.14436866,0 C5.46569585,0 4.9155023,0.531003745 4.9155023,1.18600562 L4.9155023,2.37201124 L7.37327189,2.37201124 L7.37327189,3.58050375 C3.24888479,3.88325843 0,7.20900562 0,11.2671779 C0,15.524779 3.5762212,18.9762678 7.9877235,18.9762678 C12.3992258,18.9762678 15.975447,15.524779 15.975447,11.2671779 C15.9754101,7.2090412 12.7265253,3.88332959 8.60213825,3.58050375 L8.60213825,3.58050375 Z M12.332424,15.4603783 C11.1719078,16.5804176 9.62897696,17.1972416 7.9877235,17.1972416 C6.34647005,17.1972416 4.8035023,16.5804176 3.64294931,15.4603783 C2.48243318,14.340339 1.84331797,12.8511161 1.84331797,11.2671779 C1.84331797,9.68320412 2.48247005,8.19401685 3.64294931,7.07397753 C4.75738249,5.99841386 6.22451613,5.38728277 7.79262673,5.34038764 L7.37636866,11.1596891 C7.34064516,11.6468933 7.61570507,11.8601985 7.98768664,11.8601985 C8.3596682,11.8601985 8.63476498,11.6468933 8.59896774,11.1596891 L8.18278341,5.34035206 C9.75085714,5.38728277 11.2180276,5.99844944 12.3324608,7.07397753 C13.4930507,8.19401685 14.132129,9.68320412 14.132129,11.2671779 C14.1320922,12.8511161 13.492977,14.340339 12.332424,15.4603783 L12.332424,15.4603783 Z" id=""
              span
                = project.title

        li
          = link_to "new project", new_project_url


main class="main"
  .wrapper
    h1
      = @current_project.title

    = react_component("TaskBox", { presenter: @tasks_presenter.to_json, prerender: true})

    == pagy_nav(@pagy)